name: eats
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dots_indicator: ^2.1.1
  path_provider: ^2.1.2
  path: ^1.8.3
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  badges: ^2.0.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.3.2+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/


